/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait AccountsKeyManagementApi: Send + Sync {
    /// GET /accounts/key-connector/confirmation-details/{orgSsoIdentifier}
    async fn get_key_connector_confirmation_details<'a>(
        &self,
        org_sso_identifier: &'a str,
    ) -> Result<models::KeyConnectorConfirmationDetailsResponseModel, Error>;

    /// GET /accounts/key-management/key-rotation-data
    async fn get_key_rotation_data(&self) -> Result<models::KeyRotationDataResponseModel, Error>;

    /// POST /accounts/key-management/rotate-user-account-keys
    async fn password_change_and_rotate_user_account_keys<'a>(
        &self,
        rotate_user_account_keys_and_data_request_model: Option<
            models::RotateUserAccountKeysAndDataRequestModel,
        >,
    ) -> Result<(), Error>;

    /// POST /accounts/convert-to-key-connector
    async fn post_convert_to_key_connector(&self) -> Result<(), Error>;

    /// POST /accounts/key-connector/enroll
    async fn post_enroll_to_key_connector<'a>(
        &self,
        key_connector_enrollment_request_model: Option<models::KeyConnectorEnrollmentRequestModel>,
    ) -> Result<(), Error>;

    /// POST /accounts/set-key-connector-key
    async fn post_set_key_connector_key<'a>(
        &self,
        set_key_connector_key_request_model: Option<models::SetKeyConnectorKeyRequestModel>,
    ) -> Result<(), Error>;

    /// POST /accounts/key-management/user-key-id
    /// This is meant for backfilling the user-key id for existing users for whom the key id is not
    /// yet recorded.
    async fn post_user_key_id<'a>(
        &self,
        set_user_key_id_request_model: Option<models::SetUserKeyIdRequestModel>,
    ) -> Result<(), Error>;

    /// POST /accounts/key-management/regenerate-keys
    async fn regenerate_keys<'a>(
        &self,
        key_regeneration_request_model: Option<models::KeyRegenerationRequestModel>,
    ) -> Result<(), Error>;

    /// POST /accounts/key-management/rotate-user-keys
    async fn rotate_user_keys<'a>(
        &self,
        rotate_user_keys_request_model: Option<models::RotateUserKeysRequestModel>,
    ) -> Result<(), Error>;
}

pub struct AccountsKeyManagementApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl AccountsKeyManagementApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl AccountsKeyManagementApi for AccountsKeyManagementApiClient {
    async fn get_key_connector_confirmation_details<'a>(
        &self,
        org_sso_identifier: &'a str,
    ) -> Result<models::KeyConnectorConfirmationDetailsResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/key-connector/confirmation-details/{orgSsoIdentifier}",
            local_var_configuration.base_path,
            orgSsoIdentifier = crate::apis::urlencode(org_sso_identifier)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_key_rotation_data(&self) -> Result<models::KeyRotationDataResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/key-management/key-rotation-data",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn password_change_and_rotate_user_account_keys<'a>(
        &self,
        rotate_user_account_keys_and_data_request_model: Option<
            models::RotateUserAccountKeysAndDataRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/key-management/rotate-user-account-keys",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&rotate_user_account_keys_and_data_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn post_convert_to_key_connector(&self) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/convert-to-key-connector",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn post_enroll_to_key_connector<'a>(
        &self,
        key_connector_enrollment_request_model: Option<models::KeyConnectorEnrollmentRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/key-connector/enroll",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&key_connector_enrollment_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn post_set_key_connector_key<'a>(
        &self,
        set_key_connector_key_request_model: Option<models::SetKeyConnectorKeyRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/set-key-connector-key",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&set_key_connector_key_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    /// This is meant for backfilling the user-key id for existing users for whom the key id is not
    /// yet recorded.
    async fn post_user_key_id<'a>(
        &self,
        set_user_key_id_request_model: Option<models::SetUserKeyIdRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/key-management/user-key-id",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&set_user_key_id_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn regenerate_keys<'a>(
        &self,
        key_regeneration_request_model: Option<models::KeyRegenerationRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/key-management/regenerate-keys",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&key_regeneration_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn rotate_user_keys<'a>(
        &self,
        rotate_user_keys_request_model: Option<models::RotateUserKeysRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/key-management/rotate-user-keys",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&rotate_user_keys_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }
}
