/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait FoldersApi: Send + Sync {
    /// DELETE /folders/{id}
    async fn delete<'a>(&self, id: &'a str) -> Result<(), Error>;

    /// DELETE /folders/all
    async fn delete_all(&self) -> Result<(), Error>;

    /// DELETE /folders
    async fn delete_many<'a>(
        &self,
        folder_bulk_delete_request_model: Option<models::FolderBulkDeleteRequestModel>,
    ) -> Result<(), Error>;

    /// GET /folders/{id}
    async fn get<'a>(&self, id: &'a str) -> Result<models::FolderResponseModel, Error>;

    /// GET /folders
    async fn get_all(&self) -> Result<models::FolderResponseModelListResponseModel, Error>;

    /// POST /folders
    async fn post<'a>(
        &self,
        folder_request_model: Option<models::FolderRequestModel>,
    ) -> Result<models::FolderResponseModel, Error>;

    /// PUT /folders/{id}
    async fn put<'a>(
        &self,
        id: &'a str,
        folder_request_model: Option<models::FolderRequestModel>,
    ) -> Result<models::FolderResponseModel, Error>;
}

pub struct FoldersApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl FoldersApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl FoldersApi for FoldersApiClient {
    async fn delete<'a>(&self, id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/folders/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn delete_all(&self) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/folders/all", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn delete_many<'a>(
        &self,
        folder_bulk_delete_request_model: Option<models::FolderBulkDeleteRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/folders", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&folder_bulk_delete_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get<'a>(&self, id: &'a str) -> Result<models::FolderResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/folders/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_all(&self) -> Result<models::FolderResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/folders", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn post<'a>(
        &self,
        folder_request_model: Option<models::FolderRequestModel>,
    ) -> Result<models::FolderResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/folders", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&folder_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn put<'a>(
        &self,
        id: &'a str,
        folder_request_model: Option<models::FolderRequestModel>,
    ) -> Result<models::FolderResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/folders/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&folder_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }
}
