/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait OrganizationUsersApi: Send + Sync {
    /// POST /organizations/{orgId}/users/{organizationUserId}/accept
    async fn accept<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_id: uuid::Uuid,
        organization_user_accept_request_model: Option<models::OrganizationUserAcceptRequestModel>,
    ) -> Result<(), Error>;

    /// POST /organizations/{orgId}/users/{organizationUserId}/accept-init
    async fn accept_init<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_id: uuid::Uuid,
        organization_user_accept_init_request_model: Option<
            models::OrganizationUserAcceptInitRequestModel,
        >,
    ) -> Result<(), Error>;

    /// POST /organizations/users/invite-link/accept
    async fn accept_invite_link<'a>(
        &self,
        accept_organization_invite_link_request_model: Option<
            models::AcceptOrganizationInviteLinkRequestModel,
        >,
    ) -> Result<(), Error>;

    /// POST /organizations/{orgId}/users/{id}/auto-confirm
    async fn automatically_confirm_organization_user<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        organization_user_confirm_request_model: Option<
            models::OrganizationUserConfirmRequestModel,
        >,
    ) -> Result<(), Error>;

    /// POST /organizations/{orgId}/users/bulk-auto-confirm
    async fn bulk_automatically_confirm_organization_users<'a>(
        &self,
        org_id: &'a str,
        organization: Option<models::Organization>,
        organization_user_bulk_confirm_request_model: Option<
            models::OrganizationUserBulkConfirmRequestModel,
        >,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error>;

    /// POST /organizations/{orgId}/users/confirm
    async fn bulk_confirm<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_confirm_request_model: Option<
            models::OrganizationUserBulkConfirmRequestModel,
        >,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error>;

    /// DELETE /organizations/{orgId}/users/delete-account
    async fn bulk_delete_account<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error>;

    /// PUT /organizations/{orgId}/users/enable-pam
    async fn bulk_enable_pam<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<(), Error>;

    /// PUT /organizations/{orgId}/users/enable-secrets-manager
    async fn bulk_enable_secrets_manager<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<(), Error>;

    /// POST /organizations/{orgId}/users/reinvite
    async fn bulk_reinvite<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error>;

    /// DELETE /organizations/{orgId}/users
    async fn bulk_remove<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error>;

    /// PUT /organizations/{orgId}/users/restore
    async fn bulk_restore<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error>;

    /// PUT /organizations/{orgId}/users/revoke
    async fn bulk_revoke<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error>;

    /// POST /organizations/{orgId}/users/{id}/confirm
    async fn confirm<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        organization_user_confirm_request_model: Option<
            models::OrganizationUserConfirmRequestModel,
        >,
    ) -> Result<(), Error>;

    /// POST /organizations/users/invite-link/confirm
    async fn confirm_invite_link<'a>(
        &self,
        confirm_organization_invite_link_request_model: Option<
            models::ConfirmOrganizationInviteLinkRequestModel,
        >,
    ) -> Result<(), Error>;

    /// DELETE /organizations/{orgId}/users/{id}/delete-account
    async fn delete_account<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error>;

    /// GET /organizations/{orgId}/users/{id}
    async fn get<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        include_groups: Option<bool>,
    ) -> Result<models::OrganizationUserDetailsResponseModel, Error>;

    /// POST /organizations/{orgId}/users/account-recovery-details
    async fn get_account_recovery_details<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserResetPasswordDetailsResponseModelListResponseModel, Error>;

    /// GET /organizations/{orgId}/users
    async fn get_all<'a>(
        &self,
        org_id: uuid::Uuid,
        include_groups: Option<bool>,
        include_collections: Option<bool>,
    ) -> Result<models::OrganizationUserUserDetailsResponseModelListResponseModel, Error>;

    /// POST /organizations/users/invite-link/invite
    async fn get_invite<'a>(
        &self,
        get_organization_invite_request_model: Option<models::GetOrganizationInviteRequestModel>,
    ) -> Result<models::OrganizationInviteResponseModel, Error>;

    /// GET /organizations/{orgId}/users/mini-details
    async fn get_mini_details<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationUserUserMiniDetailsResponseModelListResponseModel, Error>;

    /// GET /organizations/{orgId}/users/pending-auto-confirm
    async fn get_pending_auto_confirm_users<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationUserPendingAutoConfirmResponseModelListResponseModel, Error>;

    /// GET /organizations/{orgId}/users/{id}/reset-password-details
    async fn get_reset_password_details<'a>(
        &self,
        id: uuid::Uuid,
        org_id: &'a str,
        organization: Option<models::Organization>,
    ) -> Result<models::OrganizationUserResetPasswordDetailsResponseModel, Error>;

    /// POST /organizations/{orgId}/users/invite
    async fn invite<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_invite_request_model: Option<models::OrganizationUserInviteRequestModel>,
    ) -> Result<(), Error>;

    /// PUT /organizations/{orgId}/users/{id}
    async fn put<'a>(
        &self,
        id: uuid::Uuid,
        org_id: &'a str,
        organization: Option<models::Organization>,
        organization_user_update_request_model: Option<models::OrganizationUserUpdateRequestModel>,
    ) -> Result<(), Error>;

    /// PUT /organizations/{orgId}/users/{userId}/reset-password-enrollment
    async fn put_reset_password_enrollment<'a>(
        &self,
        org_id: uuid::Uuid,
        user_id: uuid::Uuid,
        organization_user_reset_password_enrollment_request_model: Option<
            models::OrganizationUserResetPasswordEnrollmentRequestModel,
        >,
    ) -> Result<(), Error>;

    /// PUT /organizations/{orgId}/users/{id}/recover-account
    async fn recover_account<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        target_organization_user: Option<models::OrganizationUser>,
        organization_user_reset_password_request_model: Option<
            models::OrganizationUserResetPasswordRequestModel,
        >,
    ) -> Result<(), Error>;

    /// POST /organizations/{orgId}/users/{id}/reinvite
    async fn reinvite<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error>;

    /// DELETE /organizations/{orgId}/users/{id}
    async fn remove<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error>;

    /// PUT /organizations/{orgId}/users/{id}/restore/vnext
    async fn restore_async_v_next<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        organization_user_restore_request: Option<models::OrganizationUserRestoreRequest>,
    ) -> Result<(), Error>;

    /// PUT /organizations/{orgId}/users/{id}/revoke
    async fn revoke<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error>;

    /// PUT /organizations/{orgId}/users/revoke-self
    async fn revoke_self<'a>(&self, org_id: uuid::Uuid) -> Result<(), Error>;

    /// POST /organizations/{orgId}/users/public-keys
    async fn user_public_keys<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserPublicKeyResponseModelListResponseModel, Error>;
}

pub struct OrganizationUsersApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OrganizationUsersApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl OrganizationUsersApi for OrganizationUsersApiClient {
    async fn accept<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_id: uuid::Uuid,
        organization_user_accept_request_model: Option<models::OrganizationUserAcceptRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{organizationUserId}/accept",
            local_var_configuration.base_path,
            orgId = org_id,
            organizationUserId = organization_user_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_accept_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn accept_init<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_id: uuid::Uuid,
        organization_user_accept_init_request_model: Option<
            models::OrganizationUserAcceptInitRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{organizationUserId}/accept-init",
            local_var_configuration.base_path,
            orgId = org_id,
            organizationUserId = organization_user_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_accept_init_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn accept_invite_link<'a>(
        &self,
        accept_organization_invite_link_request_model: Option<
            models::AcceptOrganizationInviteLinkRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/users/invite-link/accept",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&accept_organization_invite_link_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn automatically_confirm_organization_user<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        organization_user_confirm_request_model: Option<
            models::OrganizationUserConfirmRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/auto-confirm",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_confirm_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn bulk_automatically_confirm_organization_users<'a>(
        &self,
        org_id: &'a str,
        organization: Option<models::Organization>,
        organization_user_bulk_confirm_request_model: Option<
            models::OrganizationUserBulkConfirmRequestModel,
        >,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/bulk-auto-confirm",
            local_var_configuration.base_path,
            orgId = crate::apis::urlencode(org_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = organization {
            local_var_req_builder = local_var_req_builder
                .query(&[("organization", &serde_json::to_value(param_value)?)]);
        }
        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_bulk_confirm_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn bulk_confirm<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_confirm_request_model: Option<
            models::OrganizationUserBulkConfirmRequestModel,
        >,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/confirm",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_bulk_confirm_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn bulk_delete_account<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/delete-account",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn bulk_enable_pam<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/enable-pam",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn bulk_enable_secrets_manager<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/enable-secrets-manager",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn bulk_reinvite<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/reinvite",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn bulk_remove<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn bulk_restore<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/restore",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn bulk_revoke<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserBulkResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/revoke",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn confirm<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        organization_user_confirm_request_model: Option<
            models::OrganizationUserConfirmRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/confirm",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_confirm_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn confirm_invite_link<'a>(
        &self,
        confirm_organization_invite_link_request_model: Option<
            models::ConfirmOrganizationInviteLinkRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/users/invite-link/confirm",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&confirm_organization_invite_link_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn delete_account<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/delete-account",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        include_groups: Option<bool>,
    ) -> Result<models::OrganizationUserDetailsResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = include_groups {
            local_var_req_builder =
                local_var_req_builder.query(&[("includeGroups", &param_value.to_string())]);
        }
        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_account_recovery_details<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserResetPasswordDetailsResponseModelListResponseModel, Error>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/account-recovery-details",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_all<'a>(
        &self,
        org_id: uuid::Uuid,
        include_groups: Option<bool>,
        include_collections: Option<bool>,
    ) -> Result<models::OrganizationUserUserDetailsResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = include_groups {
            local_var_req_builder =
                local_var_req_builder.query(&[("includeGroups", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include_collections {
            local_var_req_builder =
                local_var_req_builder.query(&[("includeCollections", &param_value.to_string())]);
        }
        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_invite<'a>(
        &self,
        get_organization_invite_request_model: Option<models::GetOrganizationInviteRequestModel>,
    ) -> Result<models::OrganizationInviteResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/users/invite-link/invite",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&get_organization_invite_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_mini_details<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationUserUserMiniDetailsResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/mini-details",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_pending_auto_confirm_users<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationUserPendingAutoConfirmResponseModelListResponseModel, Error>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/pending-auto-confirm",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_reset_password_details<'a>(
        &self,
        id: uuid::Uuid,
        org_id: &'a str,
        organization: Option<models::Organization>,
    ) -> Result<models::OrganizationUserResetPasswordDetailsResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/reset-password-details",
            local_var_configuration.base_path,
            id = id,
            orgId = crate::apis::urlencode(org_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = organization {
            local_var_req_builder = local_var_req_builder
                .query(&[("organization", &serde_json::to_value(param_value)?)]);
        }
        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn invite<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_invite_request_model: Option<models::OrganizationUserInviteRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/invite",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_invite_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn put<'a>(
        &self,
        id: uuid::Uuid,
        org_id: &'a str,
        organization: Option<models::Organization>,
        organization_user_update_request_model: Option<models::OrganizationUserUpdateRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}",
            local_var_configuration.base_path,
            id = id,
            orgId = crate::apis::urlencode(org_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref param_value) = organization {
            local_var_req_builder = local_var_req_builder
                .query(&[("organization", &serde_json::to_value(param_value)?)]);
        }
        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_update_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn put_reset_password_enrollment<'a>(
        &self,
        org_id: uuid::Uuid,
        user_id: uuid::Uuid,
        organization_user_reset_password_enrollment_request_model: Option<
            models::OrganizationUserResetPasswordEnrollmentRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{userId}/reset-password-enrollment",
            local_var_configuration.base_path,
            orgId = org_id,
            userId = user_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_reset_password_enrollment_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn recover_account<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        target_organization_user: Option<models::OrganizationUser>,
        organization_user_reset_password_request_model: Option<
            models::OrganizationUserResetPasswordRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/recover-account",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref param_value) = target_organization_user {
            local_var_req_builder = local_var_req_builder.query(&[(
                "targetOrganizationUser",
                &serde_json::to_value(param_value)?,
            )]);
        }
        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_reset_password_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn reinvite<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/reinvite",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn remove<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn restore_async_v_next<'a>(
        &self,
        org_id: uuid::Uuid,
        id: uuid::Uuid,
        organization_user_restore_request: Option<models::OrganizationUserRestoreRequest>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/restore/vnext",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_restore_request);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn revoke<'a>(&self, org_id: uuid::Uuid, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/{id}/revoke",
            local_var_configuration.base_path,
            orgId = org_id,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn revoke_self<'a>(&self, org_id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/revoke-self",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn user_public_keys<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_bulk_request_model: Option<models::OrganizationUserBulkRequestModel>,
    ) -> Result<models::OrganizationUserPublicKeyResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/public-keys",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_bulk_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }
}
