/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait OrganizationBillingVNextApi: Send + Sync {
    /// POST /organizations/{organizationId}/billing/vnext/credit/bitpay
    async fn add_credit_via_bit_pay<'a>(
        &self,
        organization_id: &'a str,
        bit_pay_credit_request: Option<models::BitPayCreditRequest>,
    ) -> Result<(), Error>;

    /// GET /organizations/{organizationId}/billing/vnext/annual-upgrade-offer
    async fn get_annual_upgrade_offer<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// GET /organizations/{organizationId}/billing/vnext/address
    async fn get_billing_address<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// GET /organizations/{organizationId}/billing/vnext/churn-mitigation-offer
    async fn get_churn_mitigation_offer<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// GET /organizations/{organizationId}/billing/vnext/credit
    async fn get_credit<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// GET /organizations/{organizationId}/billing/vnext/metadata
    async fn get_metadata<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// GET /organizations/{organizationId}/billing/vnext/payment-method
    async fn get_payment_method<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// GET /organizations/{organizationId}/billing/vnext/warnings
    async fn get_warnings<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// POST /organizations/{organizationId}/billing/vnext/annual-upgrade-offer/redeem
    async fn redeem_annual_upgrade_offer<'a>(&self, organization_id: &'a str) -> Result<(), Error>;

    /// POST /organizations/{organizationId}/billing/vnext/churn-mitigation-offer/redeem
    async fn redeem_churn_mitigation_offer<'a>(
        &self,
        organization_id: &'a str,
    ) -> Result<(), Error>;

    /// POST /organizations/{organizationId}/billing/vnext/subscription/restart
    async fn restart_subscription<'a>(
        &self,
        organization_id: &'a str,
        restart_subscription_request: Option<models::RestartSubscriptionRequest>,
    ) -> Result<(), Error>;

    /// PUT /organizations/{organizationId}/billing/vnext/address
    async fn update_billing_address<'a>(
        &self,
        organization_id: &'a str,
        billing_address_request: Option<models::BillingAddressRequest>,
    ) -> Result<(), Error>;

    /// PUT /organizations/{organizationId}/billing/vnext/payment-method
    async fn update_payment_method<'a>(
        &self,
        organization_id: &'a str,
        tokenized_payment_method_request: Option<models::TokenizedPaymentMethodRequest>,
    ) -> Result<(), Error>;
}

pub struct OrganizationBillingVNextApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OrganizationBillingVNextApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl OrganizationBillingVNextApi for OrganizationBillingVNextApiClient {
    async fn add_credit_via_bit_pay<'a>(
        &self,
        organization_id: &'a str,
        bit_pay_credit_request: Option<models::BitPayCreditRequest>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/credit/bitpay",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&bit_pay_credit_request);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_annual_upgrade_offer<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/annual-upgrade-offer",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_billing_address<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/address",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_churn_mitigation_offer<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/churn-mitigation-offer",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_credit<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/credit",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_metadata<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/metadata",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_payment_method<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/payment-method",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_warnings<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/warnings",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn redeem_annual_upgrade_offer<'a>(&self, organization_id: &'a str) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/annual-upgrade-offer/redeem",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn redeem_churn_mitigation_offer<'a>(
        &self,
        organization_id: &'a str,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/churn-mitigation-offer/redeem",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn restart_subscription<'a>(
        &self,
        organization_id: &'a str,
        restart_subscription_request: Option<models::RestartSubscriptionRequest>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/subscription/restart",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&restart_subscription_request);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn update_billing_address<'a>(
        &self,
        organization_id: &'a str,
        billing_address_request: Option<models::BillingAddressRequest>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/address",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&billing_address_request);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn update_payment_method<'a>(
        &self,
        organization_id: &'a str,
        tokenized_payment_method_request: Option<models::TokenizedPaymentMethodRequest>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/billing/vnext/payment-method",
            local_var_configuration.base_path,
            organizationId = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&tokenized_payment_method_request);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }
}
