[package]
name = "bitwarden-generators"
description = """
Internal crate for the bitwarden crate. Do not use.
"""

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license = "GPL-3.0-only OR LicenseRef-Bitwarden-SDK"
keywords.workspace = true

[features]
alias = ["dep:bitwarden-alias", "dep:bitwarden-sensitive-value"]
uniffi = ["dep:uniffi"]
wasm = ["bitwarden-core/wasm", "dep:tsify", "dep:wasm-bindgen"]

[dependencies]
bitwarden-alias = { workspace = true, optional = true }
bitwarden-core = { workspace = true, features = ["internal"] }
bitwarden-crypto = { workspace = true }
bitwarden-error = { workspace = true }
bitwarden-random = { workspace = true }
bitwarden-sensitive-value = { workspace = true, optional = true }
password-rules-parser = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tsify = { workspace = true, optional = true }
uniffi = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
bitwarden-api-base = { workspace = true }
rand_chacha = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
wiremock = { workspace = true }

[lints]
workspace = true
