/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Visitor};

use crate::models;
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum AccessLeaseStatus {
    Active,
    Expired,
    Revoked,
    Cancelled,

    /// Unknown value returned from the server. This is used to handle forward compatibility.
    __Unknown(i64),
}

impl AccessLeaseStatus {
    pub fn as_i64(&self) -> i64 {
        match self {
            Self::Active => 0,
            Self::Expired => 1,
            Self::Revoked => 2,
            Self::Cancelled => 3,
            Self::__Unknown(v) => *v,
        }
    }

    pub fn from_i64(value: i64) -> Self {
        match value {
            0 => Self::Active,
            1 => Self::Expired,
            2 => Self::Revoked,
            3 => Self::Cancelled,
            v => Self::__Unknown(v),
        }
    }
}

impl serde::Serialize for AccessLeaseStatus {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_i64(self.as_i64())
    }
}

impl<'de> serde::Deserialize<'de> for AccessLeaseStatus {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct AccessLeaseStatusVisitor;

        impl Visitor<'_> for AccessLeaseStatusVisitor {
            type Value = AccessLeaseStatus;

            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("an integer")
            }

            fn visit_i64<E: serde::de::Error>(self, v: i64) -> Result<Self::Value, E> {
                Ok(AccessLeaseStatus::from_i64(v))
            }

            fn visit_u64<E: serde::de::Error>(self, v: u64) -> Result<Self::Value, E> {
                Ok(AccessLeaseStatus::from_i64(v as i64))
            }
        }

        deserializer.deserialize_i64(AccessLeaseStatusVisitor)
    }
}

impl std::fmt::Display for AccessLeaseStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_i64())
    }
}
impl Default for AccessLeaseStatus {
    fn default() -> AccessLeaseStatus {
        Self::Active
    }
}
