/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessRuleRequestModel {
    /// The rule's display name, shown wherever rules are listed and managed. Required; up to 256
    /// characters.
    #[serde(rename = "name", alias = "Name")]
    pub name: String,
    /// Optional free-text describing the rule's intent. Has no effect on evaluation; surfaced to
    /// admins only.
    #[serde(
        rename = "description",
        alias = "Description",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<String>,
    /// When false, the rule is inactive and does not gate access for the collections it governs.
    /// Defaults to true so a request that omits the field creates an active rule.
    #[serde(
        rename = "enabled",
        alias = "Enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub enabled: Option<bool>,
    /// The conditions that decide how access is granted under this rule — for example requiring
    /// human approval, or restricting to certain source IPs. Sent as a JSON array of condition
    /// objects and stored verbatim. Required — a null or omitted value is rejected; an empty array
    /// means the rule imposes no conditions, so requests under it resolve automatically.
    #[serde(rename = "conditions", alias = "Conditions")]
    pub conditions: Option<serde_json::Value>,
    /// When true, the rule enforces a per-cipher singleton (at most one active lease per cipher
    /// across all users).
    #[serde(
        rename = "singleActiveLease",
        alias = "SingleActiveLease",
        skip_serializing_if = "Option::is_none"
    )]
    pub single_active_lease: Option<bool>,
    /// Default lease duration in seconds, used to pre-fill a request opened under this rule. Null
    /// means the backend default applies.
    #[serde(
        rename = "defaultLeaseDurationSeconds",
        alias = "DefaultLeaseDurationSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_lease_duration_seconds: Option<i32>,
    /// Hard ceiling on the duration of any single lease granted under this rule, in seconds. Null
    /// means no per-rule cap.
    #[serde(
        rename = "maxLeaseDurationSeconds",
        alias = "MaxLeaseDurationSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_lease_duration_seconds: Option<i32>,
    /// When true, a member holding an active lease under this rule may extend it once (always
    /// auto-approved), by up to
    /// Bit.Services.Pam.Api.Models.Request.AccessRuleRequestModel.MaxExtensionDurationSeconds.
    #[serde(
        rename = "allowsExtensions",
        alias = "AllowsExtensions",
        skip_serializing_if = "Option::is_none"
    )]
    pub allows_extensions: Option<bool>,
    /// The longest a single extension may run, in seconds. Required to be positive when
    /// Bit.Services.Pam.Api.Models.Request.AccessRuleRequestModel.AllowsExtensions is true.
    #[serde(
        rename = "maxExtensionDurationSeconds",
        alias = "MaxExtensionDurationSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_extension_duration_seconds: Option<i32>,
    /// The complete set of collections this rule governs. The rule's associations are replaced to
    /// match exactly this set; an empty array clears all associations.
    #[serde(rename = "collections", alias = "Collections")]
    pub collections: Vec<uuid::Uuid>,
}

impl AccessRuleRequestModel {
    pub fn new(
        name: String,
        conditions: Option<serde_json::Value>,
        collections: Vec<uuid::Uuid>,
    ) -> AccessRuleRequestModel {
        AccessRuleRequestModel {
            name,
            description: None,
            enabled: None,
            conditions,
            single_active_lease: None,
            default_lease_duration_seconds: None,
            max_lease_duration_seconds: None,
            allows_extensions: None,
            max_extension_duration_seconds: None,
            collections,
        }
    }
}
