/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// AccessDecisionRequestModel : An approver's decision on a pending access request.
/// Bit.Services.Pam.Api.Models.Request.AccessDecisionRequestModel.Verdict is the
/// Bit.Pam.Enums.AccessDecisionVerdict value on the wire (`0` = deny, `1` = approve);
/// Bit.Services.Pam.Api.Models.Request.AccessDecisionRequestModel.Comment is optional.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessDecisionRequestModel {
    #[serde(rename = "verdict", alias = "Verdict")]
    pub verdict: models::AccessDecisionVerdict,
    /// An optional note recorded with the decision — for example the reason for a denial. Surfaced
    /// to the requester.
    #[serde(
        rename = "comment",
        alias = "Comment",
        skip_serializing_if = "Option::is_none"
    )]
    pub comment: Option<String>,
}

impl AccessDecisionRequestModel {
    /// An approver's decision on a pending access request.
    /// Bit.Services.Pam.Api.Models.Request.AccessDecisionRequestModel.Verdict is the
    /// Bit.Pam.Enums.AccessDecisionVerdict value on the wire (`0` = deny, `1` = approve);
    /// Bit.Services.Pam.Api.Models.Request.AccessDecisionRequestModel.Comment is optional.
    pub fn new(verdict: models::AccessDecisionVerdict) -> AccessDecisionRequestModel {
        AccessDecisionRequestModel {
            verdict,
            comment: None,
        }
    }
}
