/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Visitor};

use crate::models;
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum AccessRequestStatus {
    Pending,
    Approved,
    Denied,
    Cancelled,
    Expired,

    /// Unknown value returned from the server. This is used to handle forward compatibility.
    __Unknown(i64),
}

impl AccessRequestStatus {
    pub fn as_i64(&self) -> i64 {
        match self {
            Self::Pending => 0,
            Self::Approved => 1,
            Self::Denied => 2,
            Self::Cancelled => 3,
            Self::Expired => 4,
            Self::__Unknown(v) => *v,
        }
    }

    pub fn from_i64(value: i64) -> Self {
        match value {
            0 => Self::Pending,
            1 => Self::Approved,
            2 => Self::Denied,
            3 => Self::Cancelled,
            4 => Self::Expired,
            v => Self::__Unknown(v),
        }
    }
}

impl serde::Serialize for AccessRequestStatus {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_i64(self.as_i64())
    }
}

impl<'de> serde::Deserialize<'de> for AccessRequestStatus {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct AccessRequestStatusVisitor;

        impl Visitor<'_> for AccessRequestStatusVisitor {
            type Value = AccessRequestStatus;

            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("an integer")
            }

            fn visit_i64<E: serde::de::Error>(self, v: i64) -> Result<Self::Value, E> {
                Ok(AccessRequestStatus::from_i64(v))
            }

            fn visit_u64<E: serde::de::Error>(self, v: u64) -> Result<Self::Value, E> {
                Ok(AccessRequestStatus::from_i64(v as i64))
            }
        }

        deserializer.deserialize_i64(AccessRequestStatusVisitor)
    }
}

impl std::fmt::Display for AccessRequestStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_i64())
    }
}
impl Default for AccessRequestStatus {
    fn default() -> AccessRequestStatus {
        Self::Pending
    }
}
