/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// AccessRequestDecisionResponseModel : One decision on an access request: who decided
/// (Bit.Services.Pam.Api.Models.Response.AccessRequestDecisionResponseModel.DeciderKind), their
/// identity for a human decision, the verdict, an optional comment, and when. An element of
/// Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.Decisions — the request's
/// full decision log, oldest first.              For an automatic (access-rule) decision
/// Bit.Services.Pam.Api.Models.Response.AccessRequestDecisionResponseModel.Id/Bit.Services.Pam.Api.
/// Models.Response.AccessRequestDecisionResponseModel.Name/Bit.Services.Pam.Api.Models.Response.
/// AccessRequestDecisionResponseModel.Email are null; for a human decision they carry the approver
/// (name/email denormalized by the server, null only when the user could not be resolved).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessRequestDecisionResponseModel {
    #[serde(
        rename = "deciderKind",
        alias = "DeciderKind",
        skip_serializing_if = "Option::is_none"
    )]
    pub decider_kind: Option<models::AccessDeciderKind>,
    /// The human approver's user id, or null for an automatic decision.
    #[serde(rename = "id", alias = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The human approver's display name; null for an automatic decision, or when the user could
    /// not be resolved.
    #[serde(
        rename = "name",
        alias = "Name",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<String>,
    /// The human approver's email; null for an automatic decision, or when the user could not be
    /// resolved.
    #[serde(
        rename = "email",
        alias = "Email",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<String>,
    /// The optional note the approver left with the decision.
    #[serde(
        rename = "comment",
        alias = "Comment",
        skip_serializing_if = "Option::is_none"
    )]
    pub comment: Option<String>,
    #[serde(
        rename = "verdict",
        alias = "Verdict",
        skip_serializing_if = "Option::is_none"
    )]
    pub verdict: Option<models::AccessDecisionVerdict>,
    /// When the decision was recorded (UTC).
    #[serde(
        rename = "decidedAt",
        alias = "DecidedAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub decided_at: Option<String>,
}

impl AccessRequestDecisionResponseModel {
    /// One decision on an access request: who decided
    /// (Bit.Services.Pam.Api.Models.Response.AccessRequestDecisionResponseModel.DeciderKind), their
    /// identity for a human decision, the verdict, an optional comment, and when. An element of
    /// Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.Decisions — the
    /// request's full decision log, oldest first.              For an automatic (access-rule)
    /// decision Bit.Services.Pam.Api.Models.Response.AccessRequestDecisionResponseModel.Id/Bit.
    /// Services.Pam.Api.Models.Response.AccessRequestDecisionResponseModel.Name/Bit.Services.Pam.
    /// Api.Models.Response.AccessRequestDecisionResponseModel.Email are null; for a human decision
    /// they carry the approver (name/email denormalized by the server, null only when the user
    /// could not be resolved).
    pub fn new() -> AccessRequestDecisionResponseModel {
        AccessRequestDecisionResponseModel {
            decider_kind: None,
            id: None,
            name: None,
            email: None,
            comment: None,
            verdict: None,
            decided_at: None,
        }
    }
}
