/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessRuleResponseModel {
    #[serde(
        rename = "object",
        alias = "Object",
        skip_serializing_if = "Option::is_none"
    )]
    pub object: Option<String>,
    /// The rule's unique identifier.
    #[serde(rename = "id", alias = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The organization this rule belongs to.
    #[serde(
        rename = "organizationId",
        alias = "OrganizationId",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<uuid::Uuid>,
    /// The rule's display name, shown wherever rules are listed and managed.
    #[serde(
        rename = "name",
        alias = "Name",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<String>,
    /// Optional free-text describing the rule's intent. Has no effect on evaluation; surfaced to
    /// admins only.
    #[serde(
        rename = "description",
        alias = "Description",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<String>,
    /// When false, the rule is inactive and does not gate access for the collections it governs.
    #[serde(
        rename = "enabled",
        alias = "Enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub enabled: Option<bool>,
    /// The conditions that decide how access is granted under this rule — for example requiring
    /// human approval, or restricting to certain source IPs. Returned as a JSON array of condition
    /// objects; an empty array (or null) means the rule imposes no conditions.
    #[serde(
        rename = "conditions",
        alias = "Conditions",
        skip_serializing_if = "Option::is_none"
    )]
    pub conditions: Option<serde_json::Value>,
    /// When true, the rule enforces a per-cipher singleton (at most one active lease per cipher
    /// across all users).
    #[serde(
        rename = "singleActiveLease",
        alias = "SingleActiveLease",
        skip_serializing_if = "Option::is_none"
    )]
    pub single_active_lease: Option<bool>,
    /// Default lease duration in seconds, used to pre-fill a request opened under this rule. Null
    /// means the backend default applies.
    #[serde(
        rename = "defaultLeaseDurationSeconds",
        alias = "DefaultLeaseDurationSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_lease_duration_seconds: Option<i32>,
    /// Hard ceiling on the duration of any single lease granted under this rule, in seconds. Null
    /// means no per-rule cap.
    #[serde(
        rename = "maxLeaseDurationSeconds",
        alias = "MaxLeaseDurationSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_lease_duration_seconds: Option<i32>,
    /// When true, a member holding an active lease under this rule may extend it once (always
    /// auto-approved), by up to
    /// Bit.Services.Pam.Api.Models.Response.AccessRuleResponseModel.MaxExtensionDurationSeconds.
    #[serde(
        rename = "allowsExtensions",
        alias = "AllowsExtensions",
        skip_serializing_if = "Option::is_none"
    )]
    pub allows_extensions: Option<bool>,
    /// The longest a single extension may run, in seconds. Set when
    /// Bit.Services.Pam.Api.Models.Response.AccessRuleResponseModel.AllowsExtensions is true.
    #[serde(
        rename = "maxExtensionDurationSeconds",
        alias = "MaxExtensionDurationSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_extension_duration_seconds: Option<i32>,
    /// The complete set of collections this rule governs.
    #[serde(
        rename = "collections",
        alias = "Collections",
        skip_serializing_if = "Option::is_none"
    )]
    pub collections: Option<Vec<uuid::Uuid>>,
    /// When the rule was created (UTC).
    #[serde(
        rename = "creationDate",
        alias = "CreationDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub creation_date: Option<String>,
    /// When the rule was last modified (UTC).
    #[serde(
        rename = "revisionDate",
        alias = "RevisionDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub revision_date: Option<String>,
}

impl AccessRuleResponseModel {
    pub fn new() -> AccessRuleResponseModel {
        AccessRuleResponseModel {
            object: None,
            id: None,
            organization_id: None,
            name: None,
            description: None,
            enabled: None,
            conditions: None,
            single_active_lease: None,
            default_lease_duration_seconds: None,
            max_lease_duration_seconds: None,
            allows_extensions: None,
            max_extension_duration_seconds: None,
            collections: None,
            creation_date: None,
            revision_date: None,
        }
    }
}
