/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CipherMiniResponseModel {
    #[serde(
        rename = "object",
        alias = "Object",
        skip_serializing_if = "Option::is_none"
    )]
    pub object: Option<String>,
    #[serde(rename = "id", alias = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(
        rename = "organizationId",
        alias = "OrganizationId",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<uuid::Uuid>,
    #[serde(
        rename = "type",
        alias = "R#type",
        skip_serializing_if = "Option::is_none"
    )]
    pub r#type: Option<models::CipherType>,
    #[serde(
        rename = "data",
        alias = "Data",
        skip_serializing_if = "Option::is_none"
    )]
    pub data: Option<String>,
    /// The reduced data blob returned in place of
    /// Bit.Api.Vault.Models.Response.CipherMiniResponseModel.Data when the caller can only reach
    /// this cipher through leasing-enabled collections (PAM credential leasing). Contains the
    /// encrypted title and, for logins, the encrypted URIs — never the dropped secrets. Null for
    /// full responses.
    #[serde(
        rename = "partialData",
        alias = "PartialData",
        skip_serializing_if = "Option::is_none"
    )]
    pub partial_data: Option<String>,
    #[serde(
        rename = "name",
        alias = "Name",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<String>,
    #[serde(
        rename = "notes",
        alias = "Notes",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<String>,
    #[serde(
        rename = "login",
        alias = "Login",
        skip_serializing_if = "Option::is_none"
    )]
    pub login: Option<Box<models::CipherLoginModel>>,
    #[serde(
        rename = "card",
        alias = "Card",
        skip_serializing_if = "Option::is_none"
    )]
    pub card: Option<Box<models::CipherCardModel>>,
    #[serde(
        rename = "identity",
        alias = "Identity",
        skip_serializing_if = "Option::is_none"
    )]
    pub identity: Option<Box<models::CipherIdentityModel>>,
    #[serde(
        rename = "secureNote",
        alias = "SecureNote",
        skip_serializing_if = "Option::is_none"
    )]
    pub secure_note: Option<Box<models::CipherSecureNoteModel>>,
    #[serde(
        rename = "sshKey",
        alias = "SshKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub ssh_key: Option<Box<models::CipherSshKeyModel>>,
    #[serde(
        rename = "bankAccount",
        alias = "BankAccount",
        skip_serializing_if = "Option::is_none"
    )]
    pub bank_account: Option<Box<models::CipherBankAccountModel>>,
    #[serde(
        rename = "driversLicense",
        alias = "DriversLicense",
        skip_serializing_if = "Option::is_none"
    )]
    pub drivers_license: Option<Box<models::CipherDriversLicenseModel>>,
    #[serde(
        rename = "passport",
        alias = "Passport",
        skip_serializing_if = "Option::is_none"
    )]
    pub passport: Option<Box<models::CipherPassportModel>>,
    #[serde(
        rename = "fields",
        alias = "Fields",
        skip_serializing_if = "Option::is_none"
    )]
    pub fields: Option<Vec<models::CipherFieldModel>>,
    #[serde(
        rename = "passwordHistory",
        alias = "PasswordHistory",
        skip_serializing_if = "Option::is_none"
    )]
    pub password_history: Option<Vec<models::CipherPasswordHistoryModel>>,
    #[serde(
        rename = "attachments",
        alias = "Attachments",
        skip_serializing_if = "Option::is_none"
    )]
    pub attachments: Option<Vec<models::AttachmentResponseModel>>,
    #[serde(
        rename = "organizationUseTotp",
        alias = "OrganizationUseTotp",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_use_totp: Option<bool>,
    #[serde(
        rename = "revisionDate",
        alias = "RevisionDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub revision_date: Option<String>,
    #[serde(
        rename = "creationDate",
        alias = "CreationDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub creation_date: Option<String>,
    #[serde(
        rename = "deletedDate",
        alias = "DeletedDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub deleted_date: Option<String>,
    #[serde(
        rename = "reprompt",
        alias = "Reprompt",
        skip_serializing_if = "Option::is_none"
    )]
    pub reprompt: Option<models::CipherRepromptType>,
    #[serde(rename = "key", alias = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl CipherMiniResponseModel {
    pub fn new() -> CipherMiniResponseModel {
        CipherMiniResponseModel {
            object: None,
            id: None,
            organization_id: None,
            r#type: None,
            data: None,
            partial_data: None,
            name: None,
            notes: None,
            login: None,
            card: None,
            identity: None,
            secure_note: None,
            ssh_key: None,
            bank_account: None,
            drivers_license: None,
            passport: None,
            fields: None,
            password_history: None,
            attachments: None,
            organization_use_totp: None,
            revision_date: None,
            creation_date: None,
            deleted_date: None,
            reprompt: None,
            key: None,
        }
    }
}
