/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderBulkDeleteRequestModel {
    #[serde(rename = "ids", alias = "Ids")]
    pub ids: Vec<uuid::Uuid>,
}

impl FolderBulkDeleteRequestModel {
    pub fn new(ids: Vec<uuid::Uuid>) -> FolderBulkDeleteRequestModel {
        FolderBulkDeleteRequestModel { ids }
    }
}
