/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeysRequestModel {
    #[serde(rename = "publicKey", alias = "PublicKey")]
    pub public_key: String,
    #[serde(rename = "encryptedPrivateKey", alias = "EncryptedPrivateKey")]
    pub encrypted_private_key: String,
    #[serde(
        rename = "accountKeys",
        alias = "AccountKeys",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_keys: Option<Box<models::AccountKeysRequestModel>>,
    /// Key id of the user key these account keys belong to, when the client supplied it. Absent
    /// for clients that predate the field. Only honored on the V2 path.
    #[serde(
        rename = "userKeyId",
        alias = "UserKeyId",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_key_id: Option<String>,
}

impl KeysRequestModel {
    pub fn new(public_key: String, encrypted_private_key: String) -> KeysRequestModel {
        KeysRequestModel {
            public_key,
            encrypted_private_key,
            account_keys: None,
            user_key_id: None,
        }
    }
}
