/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MasterPasswordUnlockResponseModel {
    #[serde(rename = "kdf", alias = "Kdf")]
    pub kdf: Box<models::MasterPasswordUnlockKdfResponseModel>,
    /// The user's symmetric key encrypted with their master key. Also known as
    /// \"MasterKeyWrappedUserKey\"
    #[serde(
        rename = "masterKeyEncryptedUserKey",
        alias = "MasterKeyEncryptedUserKey"
    )]
    pub master_key_encrypted_user_key: Option<String>,
    #[serde(rename = "salt", alias = "Salt")]
    pub salt: Option<String>,
    #[serde(
        rename = "containedKeyId",
        alias = "ContainedKeyId",
        skip_serializing_if = "Option::is_none"
    )]
    pub contained_key_id: Option<String>,
}

impl MasterPasswordUnlockResponseModel {
    pub fn new(
        kdf: models::MasterPasswordUnlockKdfResponseModel,
        master_key_encrypted_user_key: Option<String>,
        salt: Option<String>,
    ) -> MasterPasswordUnlockResponseModel {
        MasterPasswordUnlockResponseModel {
            kdf: Box::new(kdf),
            master_key_encrypted_user_key,
            salt,
            contained_key_id: None,
        }
    }
}
