/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// PendingAnnualUpgradeResponseModel : The scheduled annual-upgrade target for an organization that
/// redeemed the annual-upgrade offer but whose monthly-to-annual Stripe schedule has not yet
/// activated.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingAnnualUpgradeResponseModel {
    #[serde(
        rename = "plan",
        alias = "Plan",
        skip_serializing_if = "Option::is_none"
    )]
    pub plan: Option<Box<models::PlanResponseModel>>,
    /// Null when the caller may not see sensitive billing data. See
    /// `OrganizationSubscriptionResponseModel`'s hideSensitiveData branch.
    #[serde(
        rename = "lineItems",
        alias = "LineItems",
        skip_serializing_if = "Option::is_none"
    )]
    pub line_items: Option<Vec<models::BillingSubscriptionItem>>,
    #[serde(
        rename = "effectiveDate",
        alias = "EffectiveDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_date: Option<String>,
}

impl PendingAnnualUpgradeResponseModel {
    /// The scheduled annual-upgrade target for an organization that redeemed the annual-upgrade
    /// offer but whose monthly-to-annual Stripe schedule has not yet activated.
    pub fn new() -> PendingAnnualUpgradeResponseModel {
        PendingAnnualUpgradeResponseModel {
            plan: None,
            line_items: None,
            effective_date: None,
        }
    }
}
