/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetUserKeyIdRequestModel {
    /// Hex-encoded key id of the user's current user key.
    #[serde(rename = "userKeyId", alias = "UserKeyId")]
    pub user_key_id: String,
}

impl SetUserKeyIdRequestModel {
    pub fn new(user_key_id: String) -> SetUserKeyIdRequestModel {
        SetUserKeyIdRequestModel { user_key_id }
    }
}
