/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetKeyConnectorKeyRequestModel {
    #[serde(rename = "key", alias = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(
        rename = "keys",
        alias = "Keys",
        skip_serializing_if = "Option::is_none"
    )]
    pub keys: Option<Box<models::KeysRequestModel>>,
    #[serde(rename = "kdf", alias = "Kdf", skip_serializing_if = "Option::is_none")]
    pub kdf: Option<models::KdfType>,
    #[serde(
        rename = "kdfIterations",
        alias = "KdfIterations",
        skip_serializing_if = "Option::is_none"
    )]
    pub kdf_iterations: Option<i32>,
    #[serde(
        rename = "kdfMemory",
        alias = "KdfMemory",
        skip_serializing_if = "Option::is_none"
    )]
    pub kdf_memory: Option<i32>,
    #[serde(
        rename = "kdfParallelism",
        alias = "KdfParallelism",
        skip_serializing_if = "Option::is_none"
    )]
    pub kdf_parallelism: Option<i32>,
    #[serde(
        rename = "keyConnectorKeyWrappedUserKey",
        alias = "KeyConnectorKeyWrappedUserKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub key_connector_key_wrapped_user_key: Option<String>,
    #[serde(
        rename = "accountKeys",
        alias = "AccountKeys",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_keys: Option<Box<models::AccountKeysRequestModel>>,
    /// Key id of the user key wrapped by
    /// Bit.Api.KeyManagement.Models.Requests.SetKeyConnectorKeyRequestModel.
    /// KeyConnectorKeyWrappedUserKey, when the client supplied it. Absent for clients that predate
    /// the field, so it is deliberately not part of
    /// M:Bit.Api.KeyManagement.Models.Requests.SetKeyConnectorKeyRequestModel.IsV2Request.
    #[serde(
        rename = "containedKeyId",
        alias = "ContainedKeyId",
        skip_serializing_if = "Option::is_none"
    )]
    pub contained_key_id: Option<String>,
    #[serde(rename = "orgIdentifier", alias = "OrgIdentifier")]
    pub org_identifier: String,
}

impl SetKeyConnectorKeyRequestModel {
    pub fn new(org_identifier: String) -> SetKeyConnectorKeyRequestModel {
        SetKeyConnectorKeyRequestModel {
            key: None,
            keys: None,
            kdf: None,
            kdf_iterations: None,
            kdf_memory: None,
            kdf_parallelism: None,
            key_connector_key_wrapped_user_key: None,
            account_keys: None,
            contained_key_id: None,
            org_identifier,
        }
    }
}
