/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserDecryptionResponseModel {
    #[serde(
        rename = "masterPasswordUnlock",
        alias = "MasterPasswordUnlock",
        skip_serializing_if = "Option::is_none"
    )]
    pub master_password_unlock: Option<Box<models::MasterPasswordUnlockResponseModel>>,
    /// Gets or sets the WebAuthn PRF decryption keys.
    #[serde(
        rename = "webAuthnPrfOptions",
        alias = "WebAuthnPrfOptions",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_authn_prf_options: Option<Vec<models::WebAuthnPrfDecryptionOption>>,
    #[serde(
        rename = "v2UpgradeToken",
        alias = "V2UpgradeToken",
        skip_serializing_if = "Option::is_none"
    )]
    pub v2_upgrade_token: Option<Box<models::V2UpgradeTokenResponseModel>>,
    #[serde(
        rename = "userKeyId",
        alias = "UserKeyId",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_key_id: Option<String>,
}

impl UserDecryptionResponseModel {
    pub fn new() -> UserDecryptionResponseModel {
        UserDecryptionResponseModel {
            master_password_unlock: None,
            web_authn_prf_options: None,
            v2_upgrade_token: None,
            user_key_id: None,
        }
    }
}
