/*
 * Bitwarden Identity
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MasterPasswordUnlockDataRequestModel {
    #[serde(rename = "kdf", alias = "Kdf")]
    pub kdf: Box<models::KdfRequestModel>,
    #[serde(rename = "masterKeyWrappedUserKey", alias = "MasterKeyWrappedUserKey")]
    pub master_key_wrapped_user_key: String,
    #[serde(rename = "salt", alias = "Salt")]
    pub salt: String,
    #[serde(
        rename = "containedKeyId",
        alias = "ContainedKeyId",
        skip_serializing_if = "Option::is_none"
    )]
    pub contained_key_id: Option<String>,
}

impl MasterPasswordUnlockDataRequestModel {
    pub fn new(
        kdf: models::KdfRequestModel,
        master_key_wrapped_user_key: String,
        salt: String,
    ) -> MasterPasswordUnlockDataRequestModel {
        MasterPasswordUnlockDataRequestModel {
            kdf: Box::new(kdf),
            master_key_wrapped_user_key,
            salt,
            contained_key_id: None,
        }
    }
}
