/*
 * Bitwarden Identity
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterSendVerificationEmailRequestModel {
    #[serde(
        rename = "name",
        alias = "Name",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<String>,
    #[serde(rename = "email", alias = "Email")]
    pub email: Option<String>,
    #[serde(
        rename = "receiveMarketingEmails",
        alias = "ReceiveMarketingEmails",
        skip_serializing_if = "Option::is_none"
    )]
    pub receive_marketing_emails: Option<bool>,
    #[serde(
        rename = "fromMarketing",
        alias = "FromMarketing",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_marketing: Option<String>,
    #[serde(
        rename = "openOrgInvite",
        alias = "OpenOrgInvite",
        skip_serializing_if = "Option::is_none"
    )]
    pub open_org_invite: Option<Box<models::RegisterStartOpenOrgInviteRequestModel>>,
}

impl RegisterSendVerificationEmailRequestModel {
    pub fn new(email: Option<String>) -> RegisterSendVerificationEmailRequestModel {
        RegisterSendVerificationEmailRequestModel {
            name: None,
            email,
            receive_marketing_emails: None,
            from_marketing: None,
            open_org_invite: None,
        }
    }
}
