/*
 * Bitwarden Identity
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterStartOpenOrgInviteRequestModel {
    #[serde(rename = "organizationId", alias = "OrganizationId")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "code", alias = "Code")]
    pub code: uuid::Uuid,
    #[serde(rename = "sealedOpenOrgInviteData", alias = "SealedOpenOrgInviteData")]
    pub sealed_open_org_invite_data: String,
}

impl RegisterStartOpenOrgInviteRequestModel {
    pub fn new(
        organization_id: uuid::Uuid,
        code: uuid::Uuid,
        sealed_open_org_invite_data: String,
    ) -> RegisterStartOpenOrgInviteRequestModel {
        RegisterStartOpenOrgInviteRequestModel {
            organization_id,
            code,
            sealed_open_org_invite_data,
        }
    }
}
