/*
 * Bitwarden Identity
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrialSendVerificationEmailRequestModel {
    #[serde(
        rename = "name",
        alias = "Name",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<String>,
    #[serde(rename = "email", alias = "Email")]
    pub email: Option<String>,
    #[serde(
        rename = "receiveMarketingEmails",
        alias = "ReceiveMarketingEmails",
        skip_serializing_if = "Option::is_none"
    )]
    pub receive_marketing_emails: Option<bool>,
    #[serde(
        rename = "fromMarketing",
        alias = "FromMarketing",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_marketing: Option<String>,
    #[serde(
        rename = "openOrgInvite",
        alias = "OpenOrgInvite",
        skip_serializing_if = "Option::is_none"
    )]
    pub open_org_invite: Option<Box<models::RegisterStartOpenOrgInviteRequestModel>>,
    #[serde(rename = "productTier", alias = "ProductTier")]
    pub product_tier: models::ProductTierType,
    #[serde(rename = "products", alias = "Products")]
    pub products: Vec<models::ProductType>,
    #[serde(
        rename = "trialLength",
        alias = "TrialLength",
        skip_serializing_if = "Option::is_none"
    )]
    pub trial_length: Option<i32>,
    #[serde(
        rename = "paymentOptional",
        alias = "PaymentOptional",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_optional: Option<bool>,
}

impl TrialSendVerificationEmailRequestModel {
    pub fn new(
        email: Option<String>,
        product_tier: models::ProductTierType,
        products: Vec<models::ProductType>,
    ) -> TrialSendVerificationEmailRequestModel {
        TrialSendVerificationEmailRequestModel {
            name: None,
            email,
            receive_marketing_emails: None,
            from_marketing: None,
            open_org_invite: None,
            product_tier,
            products,
            trial_length: None,
            payment_optional: None,
        }
    }
}
