#!/usr/bin/env bash
set -euo pipefail

: "${SIMPLELOGIN_BASE_URL:?set by lab.sh}"
: "${SIMPLELOGIN_API_KEY:?set by lab.sh}"
: "${SIMPLELOGIN_USER_EMAIL:?set by lab.sh}"
: "${SIMPLELOGIN_LAB_SCRIPT:?set by lab.sh}"

run_id="$(python3 -c 'import time; print(time.time_ns())')"
expected_alias="sdk-lifecycle-${run_id}@sl.lan"
website="sdk-lifecycle-${run_id}.com"
updated_note="Lifecycle update persisted"
contact_email="lifecycle-contact@example.com"

api() {
  local method="$1"
  local path="$2"
  local payload="${3:-}"
  local args=(
    --silent
    --show-error
    --fail-with-body
    --request "$method"
    --header "Authentication: ${SIMPLELOGIN_API_KEY}"
  )
  if [[ -n "$payload" ]]; then
    args+=(--header "Content-Type: application/json" --data "$payload")
  fi
  curl "${args[@]}" "${SIMPLELOGIN_BASE_URL}${path}"
}

assert_jq() {
  local payload="$1"
  local expression="$2"
  local message="$3"
  if ! jq -e "$expression" >/dev/null <<<"$payload"; then
    printf 'assertion failed: %s\nresponse: %s\n' "$message" "$payload" >&2
    exit 1
  fi
}

db_scalar() {
  "$SIMPLELOGIN_LAB_SCRIPT" db-scalar "$1"
}

user_info="$(api GET /api/user_info)"
assert_jq "$user_info" ".email == \"${SIMPLELOGIN_USER_EMAIL}\"" "authenticated API readiness"

seeded_aliases="$(api GET /api/v2/aliases?page_id=0)"
assert_jq "$seeded_aliases" '[.aliases[].email] | index("seed-alpha@sl.lan") != null' "seeded alias is listed"
seed_alias_id="$(jq -r '.aliases[] | select(.email == "seed-alpha@sl.lan") | .id' <<<"$seeded_aliases")"
seeded_contacts="$(api GET "/api/aliases/${seed_alias_id}/contacts?page_id=0")"
assert_jq "$seeded_contacts" '[.contacts[].contact] | index("seed-contact@example.com") != null' "seeded contact is listed"

printf 'running the production Bitwarden SimpleLogin generator against the real service\n'
env \
  SIMPLELOGIN_REAL_BASE_URL="$SIMPLELOGIN_BASE_URL" \
  SIMPLELOGIN_REAL_API_KEY="$SIMPLELOGIN_API_KEY" \
  SIMPLELOGIN_REAL_WEBSITE="$website" \
  SIMPLELOGIN_REAL_EXPECTED_ALIAS="$expected_alias" \
  cargo test -p bitwarden-generators \
    username_forwarders::simplelogin::tests::test_real_simplelogin_service \
    -- --ignored --exact

aliases="$(api GET /api/v2/aliases?page_id=0)"
assert_jq "$aliases" "[.aliases[].email] | index(\"${expected_alias}\") != null" "SDK-created alias is listed"
alias_id="$(jq -r ".aliases[] | select(.email == \"${expected_alias}\") | .id" <<<"$aliases")"
if [[ ! "$alias_id" =~ ^[0-9]+$ ]]; then
  printf 'invalid alias id returned by SimpleLogin: %s\n' "$alias_id" >&2
  exit 1
fi
assert_jq "$aliases" ".aliases[] | select(.id == ${alias_id}) | .note == \"Website: ${website}. Generated by Bitwarden.\"" "Bitwarden note persisted"

db_note="$(db_scalar "SELECT note FROM alias WHERE id = ${alias_id};")"
[[ "$db_note" == "Website: ${website}. Generated by Bitwarden." ]] || {
  printf 'database did not persist the SDK create operation\n' >&2
  exit 1
}

api PUT "/api/aliases/${alias_id}" "$(jq -nc --arg note "$updated_note" '{note:$note,name:"Lifecycle alias",pinned:true}')" >/dev/null
alias_detail="$(api GET "/api/aliases/${alias_id}")"
assert_jq "$alias_detail" ".note == \"${updated_note}\" and .name == \"Lifecycle alias\" and .pinned == true" "alias update is visible"
[[ "$(db_scalar "SELECT note FROM alias WHERE id = ${alias_id};")" == "$updated_note" ]] || {
  printf 'database did not persist the alias update\n' >&2
  exit 1
}

toggle="$(api POST "/api/aliases/${alias_id}/toggle")"
assert_jq "$toggle" '.enabled == false' "alias toggles off"
[[ "$(db_scalar "SELECT enabled FROM alias WHERE id = ${alias_id};")" == "f" ]] || {
  printf 'database did not persist disabled alias state\n' >&2
  exit 1
}
toggle="$(api POST "/api/aliases/${alias_id}/toggle")"
assert_jq "$toggle" '.enabled == true' "alias toggles on"

contact="$(api POST "/api/aliases/${alias_id}/contacts" "$(jq -nc --arg contact "$contact_email" '{contact:$contact}')")"
assert_jq "$contact" ".contact == \"${contact_email}\" and .existed == false and (.reverse_alias_address | length > 0)" "contact and reverse alias are created"
contact_id="$(jq -r '.id' <<<"$contact")"
reverse_alias="$(jq -r '.reverse_alias_address' <<<"$contact")"
if [[ ! "$contact_id" =~ ^[0-9]+$ ]] || [[ "$reverse_alias" != *@sl.lan && "$reverse_alias" != *@aliases.sl.lan ]]; then
  printf 'invalid persisted contact or reverse alias\n' >&2
  exit 1
fi

contacts="$(api GET "/api/aliases/${alias_id}/contacts?page_id=0")"
assert_jq "$contacts" ".contacts[] | select(.id == ${contact_id}) | .reverse_alias_address == \"${reverse_alias}\"" "contact list returns reverse alias"
[[ "$(db_scalar "SELECT reply_email FROM contact WHERE id = ${contact_id};")" == "$reverse_alias" ]] || {
  printf 'database did not persist the reverse alias\n' >&2
  exit 1
}

contact_toggle="$(api POST "/api/contacts/${contact_id}/toggle")"
assert_jq "$contact_toggle" '.block_forward == true' "contact toggles blocked"
contact_toggle="$(api POST "/api/contacts/${contact_id}/toggle")"
assert_jq "$contact_toggle" '.block_forward == false' "contact toggles unblocked"

if [[ "${SIMPLELOGIN_MAIL_TEST:-0}" == "1" ]]; then
  env \
    SIMPLELOGIN_MAIL_ALIAS="$expected_alias" \
    SIMPLELOGIN_MAILBOX="$SIMPLELOGIN_USER_EMAIL" \
    SIMPLELOGIN_MAIL_CONTACT="$contact_email" \
    SIMPLELOGIN_REVERSE_ALIAS="$reverse_alias" \
    SIMPLELOGIN_SMTP_PORT="${SIMPLELOGIN_SMTP_PORT:-20381}" \
    SIMPLELOGIN_MAILPIT_URL="${SIMPLELOGIN_MAILPIT_URL:-http://127.0.0.1:18025}" \
    python3 "$(dirname "$SIMPLELOGIN_LAB_SCRIPT")/mail_lifecycle.py"

  stats="$(api GET /api/stats)"
  assert_jq "$stats" '.nb_forward >= 1 and .nb_reply >= 1' "mail lifecycle updates API statistics"
  [[ "$(db_scalar "SELECT count(*) FROM email_log WHERE alias_id = ${alias_id} AND contact_id = ${contact_id} AND is_reply = false;")" -ge 1 ]] || {
    printf 'database did not persist the forwarding activity\n' >&2
    exit 1
  }
  [[ "$(db_scalar "SELECT count(*) FROM email_log WHERE alias_id = ${alias_id} AND contact_id = ${contact_id} AND is_reply = true;")" -ge 1 ]] || {
    printf 'database did not persist the reply activity\n' >&2
    exit 1
  }
fi

deleted_contact="$(api DELETE "/api/contacts/${contact_id}")"
assert_jq "$deleted_contact" '.deleted == true' "contact deletes"
[[ "$(db_scalar "SELECT count(*) FROM contact WHERE id = ${contact_id};")" == "0" ]] || {
  printf 'database still contains deleted contact\n' >&2
  exit 1
}

deleted_alias="$(api DELETE "/api/aliases/${alias_id}")"
assert_jq "$deleted_alias" '.deleted == true' "alias deletes"
[[ "$(db_scalar "SELECT count(*) FROM alias WHERE id = ${alias_id};")" == "0" ]] || {
  printf 'database still contains deleted alias\n' >&2
  exit 1
}
aliases="$(api GET /api/v2/aliases?page_id=0)"
assert_jq "$aliases" "[.aliases[].email] | index(\"${expected_alias}\") == null" "deleted alias is absent from list"

printf 'real SimpleLogin API and database lifecycle: ok\n'
