use reqwest::StatusCode;
#[cfg(not(feature = "alias"))]
use reqwest::header::CONTENT_TYPE;

#[cfg(feature = "alias")]
use bitwarden_alias::{
    Alias, AliasClient, AliasClientSettings, AliasError, CreateRandomAliasRequest,
};
#[cfg(feature = "alias")]
use bitwarden_sensitive_value::{ExposeSensitive, SensitiveString};

use crate::username::UsernameError;

pub(crate) async fn generate(
    http: &reqwest::Client,
    api_key: String,
    base_url: String,
    website: Option<String>,
) -> Result<String, UsernameError> {
    #[cfg(feature = "alias")]
    {
        let _ = http;
        let settings =
            AliasClientSettings::new(SensitiveString::from(api_key)).with_base_url(base_url);
        let website = website.map(SensitiveString::from);
        generate_alias(settings, website)
            .await
            .map(|alias| alias.email.expose_owned())
            .map_err(map_alias_error)
    }

    #[cfg(not(feature = "alias"))]
    {
        generate_with_api_url(http, api_key, base_url, website).await
    }
}

#[cfg(feature = "alias")]
pub(crate) async fn generate_alias(
    settings: AliasClientSettings,
    website: Option<SensitiveString>,
) -> Result<Alias, AliasError> {
    let note =
        super::format_description(&website.as_ref().map(|website| website.expose().to_owned()));
    AliasClient::new(settings)?
        .create_random_alias(CreateRandomAliasRequest {
            hostname: website,
            mode: None,
            note: Some(SensitiveString::from(note)),
        })
        .await
}

#[cfg(feature = "alias")]
fn map_alias_error(error: AliasError) -> UsernameError {
    match error {
        AliasError::AuthenticationFailed | AliasError::InvalidAuthenticationToken => {
            UsernameError::InvalidApiKey
        }
        AliasError::Provider { status, message } => match StatusCode::from_u16(status) {
            Ok(status) => UsernameError::ResponseContent { status, message },
            Err(_) => UsernameError::Unknown,
        },
        AliasError::Transport(error) => UsernameError::Reqwest(error),
        AliasError::InvalidRequest(_)
        | AliasError::InvalidBaseUrl(_)
        | AliasError::RedirectRejected { .. }
        | AliasError::RateLimited { .. }
        | AliasError::ResponseTooLarge { .. }
        | AliasError::UnexpectedContentType
        | AliasError::InvalidResponse(_)
        | AliasError::InvalidResponseValue(_) => UsernameError::Unknown,
    }
}

#[cfg(not(feature = "alias"))]
async fn generate_with_api_url(
    http: &reqwest::Client,
    api_key: String,
    api_url: String,
    website: Option<String>,
) -> Result<String, UsernameError> {
    let query = website
        .as_ref()
        .map(|w| format!("?hostname={w}"))
        .unwrap_or_default();

    let note = super::format_description(&website);

    #[derive(serde::Serialize)]
    struct Request {
        note: String,
    }

    let response = http
        .post(format!("{api_url}/api/alias/random/new{query}"))
        .header(CONTENT_TYPE, "application/json")
        .header("Authentication", api_key)
        .json(&Request { note })
        .send()
        .await?;

    if response.status() == StatusCode::UNAUTHORIZED {
        return Err(UsernameError::InvalidApiKey);
    }

    // Throw any other errors
    response.error_for_status_ref()?;

    #[derive(serde::Deserialize)]
    struct Response {
        alias: String,
    }
    let response: Response = response.json().await?;

    Ok(response.alias)
}

#[cfg(test)]
mod tests {
    #[cfg(not(feature = "alias"))]
    use bitwarden_api_base::new_http_client;
    use serde_json::json;

    use crate::username::UsernameError;
    #[cfg(not(feature = "alias"))]
    #[tokio::test]
    async fn legacy_transport_without_alias_feature() {
        use wiremock::{Mock, ResponseTemplate, matchers};

        let server = wiremock::MockServer::start().await;

        // Mock the request to the SimpleLogin API, and verify that the correct request is made
        server
            .register(
                Mock::given(matchers::path("/api/alias/random/new"))
                    .and(matchers::method("POST"))
                    .and(matchers::query_param("hostname", "example.com"))
                    .and(matchers::header("Content-Type", "application/json"))
                    .and(matchers::header("Authentication", "MY_TOKEN"))
                    .and(matchers::body_json(json!({
                        "note": "Website: example.com. Generated by Bitwarden."
                    })))
                    .respond_with(ResponseTemplate::new(201).set_body_json(json!({
                        "alias": "simplelogin.yut3g8@aleeas.com",
                    })))
                    .expect(1),
            )
            .await;
        // Mock an invalid token request
        server
            .register(
                Mock::given(matchers::path("/api/alias/random/new"))
                    .and(matchers::method("POST"))
                    .and(matchers::query_param("hostname", "example.com"))
                    .and(matchers::header("Content-Type", "application/json"))
                    .and(matchers::header("Authentication", "MY_FAKE_TOKEN"))
                    .and(matchers::body_json(json!({
                        "note": "Website: example.com. Generated by Bitwarden."
                    })))
                    .respond_with(ResponseTemplate::new(401))
                    .expect(1),
            )
            .await;

        let address = super::generate_with_api_url(
            &new_http_client(),
            "MY_TOKEN".into(),
            format!("http://{}", server.address()),
            Some("example.com".into()),
        )
        .await
        .unwrap();
        assert_eq!(address, "simplelogin.yut3g8@aleeas.com");

        let fake_token_error = super::generate_with_api_url(
            &new_http_client(),
            "MY_FAKE_TOKEN".into(),
            format!("http://{}", server.address()),
            Some("example.com".into()),
        )
        .await
        .unwrap_err();

        assert_eq!(
            fake_token_error.to_string(),
            UsernameError::InvalidApiKey.to_string()
        );

        server.verify().await;
    }

    #[cfg(feature = "alias")]
    fn alias_json(id: u64, email: &str) -> serde_json::Value {
        json!({
            "id": id,
            "email": email,
            "creation_date": "2026-08-10T10:00:00+00:00",
            "creation_timestamp": 1786356000,
            "enabled": true,
            "note": "Website: example.com. Generated by Bitwarden.",
            "name": null,
            "nb_forward": 0,
            "nb_block": 0,
            "nb_reply": 0,
            "mailbox": {"id": 11, "email": "owner@example.test"},
            "mailboxes": [{"id": 11, "email": "owner@example.test"}],
            "support_pgp": false,
            "disable_pgp": false,
            "latest_activity": null,
            "pinned": false
        })
    }

    #[cfg(feature = "alias")]
    #[tokio::test]
    async fn legacy_generation_uses_alias_core_and_returns_only_address() {
        use bitwarden_api_base::new_http_client;
        use wiremock::{Mock, ResponseTemplate, matchers};

        let server = wiremock::MockServer::start().await;
        server
            .register(
                Mock::given(matchers::path("/api/alias/random/new"))
                    .and(matchers::method("POST"))
                    .and(matchers::query_param("hostname", "example.com"))
                    .and(matchers::header("Authentication", "MY_TOKEN"))
                    .and(matchers::body_json(json!({
                        "note": "Website: example.com. Generated by Bitwarden."
                    })))
                    .respond_with(
                        ResponseTemplate::new(201)
                            .set_body_json(alias_json(418, "simplelogin.yut3g8@aleeas.com")),
                    )
                    .expect(1),
            )
            .await;
        server
            .register(
                Mock::given(matchers::path("/api/alias/random/new"))
                    .and(matchers::method("POST"))
                    .and(matchers::query_param("hostname", "example.com"))
                    .and(matchers::header("Authentication", "MY_FAKE_TOKEN"))
                    .and(matchers::body_json(json!({
                        "note": "Website: example.com. Generated by Bitwarden."
                    })))
                    .respond_with(ResponseTemplate::new(401).set_body_json(json!({
                        "error": "invalid token MY_FAKE_TOKEN"
                    })))
                    .expect(1),
            )
            .await;

        let address = super::generate(
            &new_http_client(),
            "MY_TOKEN".into(),
            server.uri(),
            Some("example.com".into()),
        )
        .await
        .expect("legacy generation should succeed through alias-core");
        assert_eq!(address, "simplelogin.yut3g8@aleeas.com");

        let fake_token_error = super::generate(
            &new_http_client(),
            "MY_FAKE_TOKEN".into(),
            server.uri(),
            Some("example.com".into()),
        )
        .await
        .expect_err("invalid authentication should retain the legacy error variant");
        assert_eq!(
            fake_token_error.to_string(),
            UsernameError::InvalidApiKey.to_string()
        );
        assert!(!fake_token_error.to_string().contains("MY_FAKE_TOKEN"));

        server.verify().await;
    }

    #[cfg(feature = "alias")]
    #[tokio::test]
    async fn delegated_generation_redacts_inputs_and_strips_transport_urls() {
        use bitwarden_alias::AliasClientSettings;
        use bitwarden_sensitive_value::SensitiveString;

        const TOKEN: &str = "token-that-must-not-render";
        const HOSTNAME: &str = "hostname-that-must-not-render.example";

        let settings = AliasClientSettings::new(SensitiveString::from(TOKEN));
        let hostname = SensitiveString::from(HOSTNAME);
        assert!(!format!("{settings:?}").contains(TOKEN));
        assert!(!format!("{hostname:?}").contains(HOSTNAME));

        let server = wiremock::MockServer::start().await;
        let private_base_url = format!("{}/private-provider-path", server.uri());
        drop(server);

        let error = super::generate(
            &bitwarden_api_base::new_http_client(),
            TOKEN.to_owned(),
            private_base_url,
            Some(HOSTNAME.to_owned()),
        )
        .await
        .expect_err("a stopped provider should return a transport error");
        let rendered = error.to_string();
        assert!(!rendered.contains(TOKEN));
        assert!(!rendered.contains(HOSTNAME));
        assert!(!rendered.contains("private-provider-path"));
    }
}
