use reqwest::{StatusCode, header::CONTENT_TYPE};

use crate::username::UsernameError;

pub(crate) async fn generate(
    http: &reqwest::Client,
    api_key: String,
    base_url: String,
    website: Option<String>,
) -> Result<String, UsernameError> {
    generate_with_api_url(http, api_key, base_url, website).await
}

async fn generate_with_api_url(
    http: &reqwest::Client,
    api_key: String,
    api_url: String,
    website: Option<String>,
) -> Result<String, UsernameError> {
    let query = website
        .as_ref()
        .map(|w| format!("?hostname={w}"))
        .unwrap_or_default();

    let note = super::format_description(&website);

    #[derive(serde::Serialize)]
    struct Request {
        note: String,
    }

    let response = http
        .post(format!("{api_url}/api/alias/random/new{query}"))
        .header(CONTENT_TYPE, "application/json")
        .header("Authentication", api_key)
        .json(&Request { note })
        .send()
        .await?;

    if response.status() == StatusCode::UNAUTHORIZED {
        return Err(UsernameError::InvalidApiKey);
    }

    // Throw any other errors
    response.error_for_status_ref()?;

    #[derive(serde::Deserialize)]
    struct Response {
        alias: String,
    }
    let response: Response = response.json().await?;

    Ok(response.alias)
}

#[cfg(test)]
mod tests {
    use bitwarden_api_base::new_http_client;
    use serde_json::json;

    use crate::username::UsernameError;
    #[tokio::test]
    async fn test_mock_server() {
        use wiremock::{Mock, ResponseTemplate, matchers};

        let server = wiremock::MockServer::start().await;

        // Mock the request to the SimpleLogin API, and verify that the correct request is made
        server
            .register(
                Mock::given(matchers::path("/api/alias/random/new"))
                    .and(matchers::method("POST"))
                    .and(matchers::query_param("hostname", "example.com"))
                    .and(matchers::header("Content-Type", "application/json"))
                    .and(matchers::header("Authentication", "MY_TOKEN"))
                    .and(matchers::body_json(json!({
                        "note": "Website: example.com. Generated by Bitwarden."
                    })))
                    .respond_with(ResponseTemplate::new(201).set_body_json(json!({
                        "alias": "simplelogin.yut3g8@aleeas.com",
                    })))
                    .expect(1),
            )
            .await;
        // Mock an invalid token request
        server
            .register(
                Mock::given(matchers::path("/api/alias/random/new"))
                    .and(matchers::method("POST"))
                    .and(matchers::query_param("hostname", "example.com"))
                    .and(matchers::header("Content-Type", "application/json"))
                    .and(matchers::header("Authentication", "MY_FAKE_TOKEN"))
                    .and(matchers::body_json(json!({
                        "note": "Website: example.com. Generated by Bitwarden."
                    })))
                    .respond_with(ResponseTemplate::new(401))
                    .expect(1),
            )
            .await;

        let address = super::generate_with_api_url(
            &new_http_client(),
            "MY_TOKEN".into(),
            format!("http://{}", server.address()),
            Some("example.com".into()),
        )
        .await
        .unwrap();
        assert_eq!(address, "simplelogin.yut3g8@aleeas.com");

        let fake_token_error = super::generate_with_api_url(
            &new_http_client(),
            "MY_FAKE_TOKEN".into(),
            format!("http://{}", server.address()),
            Some("example.com".into()),
        )
        .await
        .unwrap_err();

        assert_eq!(
            fake_token_error.to_string(),
            UsernameError::InvalidApiKey.to_string()
        );

        server.verify().await;
    }

    #[tokio::test]
    #[ignore = "requires the real SimpleLogin integration lab"]
    async fn test_real_simplelogin_service() {
        let api_url = std::env::var("SIMPLELOGIN_REAL_BASE_URL")
            .expect("SIMPLELOGIN_REAL_BASE_URL must be set by the integration lab");
        let api_key = std::env::var("SIMPLELOGIN_REAL_API_KEY")
            .expect("SIMPLELOGIN_REAL_API_KEY must be set by the integration lab");
        let website = std::env::var("SIMPLELOGIN_REAL_WEBSITE")
            .expect("SIMPLELOGIN_REAL_WEBSITE must be set by the integration lab");
        let expected_alias = std::env::var("SIMPLELOGIN_REAL_EXPECTED_ALIAS")
            .expect("SIMPLELOGIN_REAL_EXPECTED_ALIAS must be set by the integration lab");

        let address =
            super::generate_with_api_url(&new_http_client(), api_key, api_url, Some(website))
                .await
                .expect("the real SimpleLogin service should create an alias");

        assert_eq!(address, expected_alias);
    }
}
