[bindings.kotlin]
package_name = "com.bitwarden.alias"
generate_immutable_records = true
android = true
# Temporary workaround for https://github.com/mozilla/uniffi-rs/issues/2740
omit_checksums = true

[bindings.swift]
ffi_module_name = "BitwardenAliasFFI"
module_name = "BitwardenAlias"
generate_immutable_records = true
